# docker-compose.yml (Final Correct Version)

networks:
  llm_toolkit_net:
    driver: bridge

services:
  webapp:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./app:/app/app
      - ./wsgi.py:/app/wsgi.py
      - ./run_cli.py:/app/run_cli.py
      - ${HF_CACHE_PATH}:/root/.cache/huggingface

    # --- THIS IS THE FIX ---
    # Instead of 'env_file', we define the environment variables directly.
    # Docker Compose will first look for these variables in the host environment
    # (which we set in the CI job). If it can't find them, it will then look
    # in a .env file in the project root. This is the perfect behavior.
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db/${MYSQL_DATABASE}
      # You can add other variables your webapp needs here, like OPENAI_API_KEY
      # For local runs, it will pick them up from your .env file.
      - OPENAI_API_KEY=${OPENAI_API_KEY}

    depends_on:
      - db
    restart: always
    networks:
      - llm_toolkit_net

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"

    # This section remains the same. It correctly uses variable substitution.
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - llm_toolkit_net

volumes:
  mysql_data:
