# docker-compose.ci.yml
# This file defines services specifically for CI tasks.

services:
  # We define a new service called 'scan' for our one-off scan task.
  scan:
    build:
      context: .

    # --- THIS IS THE CRITICAL FIX ---
    # We declaratively add the volume mount here. This is robust and reliable.
    # It mounts the 'reports' directory from the host into the container.
    volumes:
      - ./reports_output:/app/reports

      # We still need the app code mounted so the container can find run_cli.py
      # (These are inherited from the main 'webapp' service but it's good to be explicit)
      - ./app:/app/app
      - ./run_cli.py:/app/run_cli.py

    # This service depends on the 'db' service from the main compose file.
    depends_on:
      - db
